- name: Alternernatives for common CLI and shell tools.
  become: yes
  package:
      name: "{{ item }}"
      state: present
  loop:
    - bat
    - fd-find
    - ripgrep
    - git-cola
    - meld
    - tldr
    - xkill
